### ISSUE TITLE
[FEATURE] Add Analytics

### ISSUE THREAD

**Issue by sid-js** [GDSC-MVJCE/gdscmvjce-website#79]
**Is your feature request related to a problem? Please describe.**
The website does not have any analytics to keep track of visitors and other metrics.

**Describe the solution you'd like**
Add an analytics solution preferably Vercel Analytics (since the website is already hosted on Vercel) 

**Describe alternatives you've considered**
Sentry Framework

**Additional context**
Vercel Analytics Docs: https://vercel.com/docs/analytics/quickstart

**Comment by Petsamuel** [comment]
i would like to take this issue up 
if you don't mind

**Comment by Vector-ops** [comment]
I would like to work on this issue.
I have the right skills to work on this issue.
