### ISSUE TITLE
[FEATURE] - Add Analytics

### ISSUE THREAD

**Issue by sid-js** [GDSC-MVJCE/gdscmvjce-website#80]
**Is your feature request related to a problem? Please describe.**
The website does not have any analytics to keep track of visitors and other metrics.

**Describe the solution you'd like**
Add an analytics solution preferably Vercel Analytics (since the website is already hosted on Vercel) 

**Describe alternatives you've considered**
Sentry Framework

**Additional context**
Vercel Analytics Docs: https://vercel.com/docs/analytics/quickstart

**Comment by Shivam-Sharma-1** [comment]
I can do that. 
Please assign it to me.

**Comment by sid-js** [comment]
> I can do that. Please assign it to me.

Assigned the issue to you. Looking forward to it.
