### ISSUE TITLE
[FEATURE] - Adding transparency to GDSC logo canvas

### ISSUE THREAD

**Issue by Shivam-Sharma-1** [GDSC-MVJCE/gdscmvjce-website#82]
**Is your feature request related to a problem? Please describe.**
The current GDSC logo comes with a solid white background, which makes it challenging to integrate seamlessly into various digital materials and designs. This lack of transparency in the logo's canvas limits its adaptability and makes it less user-friendly for branding and promotional purposes.

**Describe the solution you'd like**
I would like the GDSC logo to have a transparent canvas/background. This change would allow for greater flexibility in using the logo across different digital platforms and materials.

**Describe alternatives you've considered**
Manually removing the white background: One alternative solution is to manually remove the white background from the logo using image editing software like Photoshop or GIMP. However, this can be time-consuming and may not yield consistent results.

**Comment by Shivam-Sharma-1** [comment]
I can do that.
Please assign it to me.

**Comment by Harishprethiv7** [comment]
I can do it.
Kindly assign it to me.

**Comment by sid-js** [comment]
@Harishprethiv7 Sorry this issue has been already resolved in #83 by @Shivam-Sharma-1 . Please feel free to create any other bug reports or feature requests and contribute :)
